
--[[Gravitas]]

template = ShipTemplate():setName("Gravitas"):setType("playership"):setClass("Frigate", "Special"):setModel("transport_1_1")
template:setDescription([[Gravitas Covert Ops Ship.]])
template:setDockClasses("Drone")
template:setRadarTrace("radar_transport.png")
template:setHull(250)
template:setShields(200, 200)
template:setSpeed(90, 10, 20)
template:setJumpDrive(false)
template:setWarpSpeed(275)
template:setCombatManeuver(400, 250)

--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0,100, -20, 1500.0, 6.0, 8)
template:setBeam(1,100,  20, 1500.0, 6.0, 8)
template:setTubes(5, 8.0) 
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 12)
template:setWeaponStorage("Nuke", 4)
template:setWeaponStorage("Mine", 8)
template:setWeaponStorage("EMP", 6)
template:setTubeDirection(0, -90)
template:setTubeDirection(1, -90)
template:setTubeDirection(2,  90)
template:setTubeDirection(3,  90)

template:setDocks(6, 2, 2, 2)
template:addDrones("L3 Mouse", 4)
template:addDrones("L3 Cat", 2)
template:addDrones("M19 Rino", 1)
template:setTractorBeam(200000, 100)

template:weaponTubeDisallowMissle(0, "Mine"):weaponTubeDisallowMissle(1, "Mine")
template:weaponTubeDisallowMissle(2, "Mine"):weaponTubeDisallowMissle(3, "Mine")
template:setTubeDirection(4, 180):setWeaponTubeExclusiveFor(4, "Mine")


--[[-----------------------Drones-----------------------]]
template = ShipTemplate():setName("L3 Mouse"):setType("drone"):setClass("Drone", "Beamer"):setModel("small_fighter_1")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[beams attack drone]])
template:setEnergyStorage(200)
template:setHull(30)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("L3 Cat"):setType("drone"):setClass("Drone", "Swoosher"):setModel("AdlerLongRangeScoutRed")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[HVLI attack drone]])
template:setEnergyStorage(200)
template:setHull(30)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
template:setTubes(1, 15.0)
template:setWeaponStorage("HVLI", 4)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("M19 Rino"):setType("drone"):setClass("Drone", "Swoosher"):setModel("LindwurmFighterYellow")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Mine layer]])
template:setEnergyStorage(300)
template:setHull(150)
template:setSpeed(40, 50, 20)
template:setCombatManeuver(400, 250)
template:setTubes(1, 15.0)
template:setWeaponStorage("Mine", 1)
template:setDefaultAI('fighter')
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

--[[-----------------------Fighters-----------------------]]
template = ShipTemplate():setName("MT52 Hornet"):setClass("Starfighter", "Interceptor"):setModel("WespeScoutYellow")
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Gen1 Fighter, old but common]])
template:setHull(30)
template:setShields(20)
template:setSpeed(120, 30, 30)
template:setCombatManeuver(600, 100)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setCombatManeuver(200, 100)
template:setWarpSpeed(500)

template = ShipTemplate():setName("MU52 Super-Hornet"):setClass("Starfighter", "Interceptor"):setModel("WespeScoutRed")
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Gen2 Fighter]])
template:setHull(40)
template:setShields(30)
template:setSpeed(130, 35, 30)
template:setCombatManeuver(600, 100)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setBeam(1, 30, 0, 700.0, 4.0, 2)
template:setTubes(1, 15.0)
template:setWeaponStorage("HVLI", 6)
template:setCombatManeuver(300, 200)
template:setWarpSpeed(100)

template = ShipTemplate():setName("Adder MK5"):setClass("Starfighter", "Gunship"):setModel("AdlerLongRangeScoutYellow")
template:setRadarTrace("radar_fighter.png")
template:setDescription([[FSN Issued advanced fighter gunship]])
template:setHull(50)
template:setShields(40)
template:setSpeed(110, 25, 25)
template:setBeam(0, 35, 0, 800, 5.0, 2.0)
template:setBeam(1, 70, 30, 600, 5.0, 2.0)
template:setBeam(2, 70, -35, 600, 5.0, 2.0)
template:setCombatManeuver(400, 250)
template:setTubes(2, 12.0)
template:setWeaponStorage("HVLI", 8)
template:setWeaponStorage("Homing", 4)
template:setTubeDirection(0, 0)
template:setTubeDirection(1, 90)
template:setTubeDirection(2, -90)
template:setWarpSpeed(80)

--[[-----------------------Corvette-----------------------]]
template = ShipTemplate():setName("Phobos T3"):setClass("Corvette", "Cruiser"):setModel("small_frigate_3")
template:setDescription([[Gen1 Corvette]])
template:setDockClasses("Drone")
template:setHull(80)
template:setShields(50, 40)
template:setSpeed(80, 10, 10)
template:setCombatManeuver(250, 150)
template:setBeamWeapon(0, 90, -15, 1200, 8, 6)
template:setBeamWeapon(1, 90,  15, 1200, 8, 6)
template:setTubes(2, 60.0)
template:setWeaponStorage("HVLI", 12)
template:setWeaponStorage("Homing", 6)
template:setTubeDirection(0, 1)
template:setTubeDirection(1, 1)
template:setWarpSpeed(150)


template = ShipTemplate():setName("Centurion"):setClass("Corvette", "Cruiser"):setModel("small_frigate_2")
template:setDescription([[Gen2 Corvette]])
template:setDockClasses("Drone")
template:setHull(120)
template:setShields(80, 60)
template:setSpeed(90, 10, 10)
template:setCombatManeuver(250, 150)
template:setBeamWeapon(0, 90, -15, 1200, 6, 6)
template:setBeamWeapon(1, 90,  15, 1200, 6, 6)
template:setTubes(2, 60.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 8)
template:setWeaponStorage("EMP", 4)
template:setTubeDirection(0, -1)
template:setTubeDirection(1,  1)
template:setWarpSpeed(200)


--[[-----------------------Frigate------------------------]]

template = ShipTemplate():setName("Havoc MK3"):setClass("Frigate", "Cruiser"):setModel("LightCorvetteRed")
template:setDescription([[Gen1 Frigate]])
template:setDockClasses("Drone")
template:setHull(120)
template:setShields(100, 80)
template:setSpeed(80, 10, 10)
template:setCombatManeuver(250, 150)
template:setBeamWeapon(0, 30, -15, 1200, 6, 6)
template:setBeamWeapon(1, 30,  15, 1200, 6, 6)
template:setBeamWeapon(1, 15,  0, 1600, 8, 8)
template:setTubes(2, 60.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 10)
template:setWeaponStorage("EMP", 6)
template:setTubeDirection(0, -1)
template:setTubeDirection(1,  1)
template:setWarpSpeed(200)

template = ShipTemplate():setName("Longbow MK5"):setClass("Frigate", "Heavy Cruiser"):setModel("LightCorvetteGrey")
template:setDescription([[Gen2 Frigate]])
template:setDockClasses("Drone")
template:setHull(150)
template:setShields(80, 60)
template:setSpeed(90, 10, 10)
template:setCombatManeuver(350, 150)
template:setBeamWeapon(0, 30, -15, 1200, 6, 6)
template:setBeamWeapon(1, 30,  15, 1200, 6, 6)
template:setBeamWeapon(1, 15,  0, 2000, 10, 0)
template:setTubes(3, 10.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 8)
template:setWeaponStorage("EMP", 4)
template:setTubeDirection(0, -1)
template:setTubeDirection(1,  1)
template:setTubeDirection(1,  180)
template:setWarpSpeed(250)


--[[-----------------------Destroyer----------------------]]

template = ShipTemplate():setName("Starhammer II"):setClass("Destroyer", "Heavy Assault"):setModel("battleship_destroyer_4_upgraded")
template:setDescription([[SOL Standard Destroyer]])
template:setRadarTrace("radar_dread.png")
template:setDockClasses("Drone")
template:setHull(200)
template:setShields(250, 250)
template:setSpeed(80, 6, 10)
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 60, -10, 2000.0, 8.0, 11)
template:setBeam(1, 60,  10, 2000.0, 8.0, 11)
template:setBeam(2, 60, -20, 1500.0, 8.0, 11)
template:setBeam(3, 60,  20, 1500.0, 8.0, 11)
template:setTubes(2, 10.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 12)
template:setWeaponStorage("EMP", 6)
template:setWarpSpeed(250)
template:setCombatManeuver(350, 150)


--[[---------------------BattleCruiser--------------------]]

template = ShipTemplate():setName("Atlantis X23"):setClass("BattleCruiser", "Spearhead"):setModel("battleship_destroyer_1_upgraded")
template:setDescription([[SOL BS]])
template:setRadarTrace("radar_dread.png")
template:setHull(250)
template:setShields(200, 200, 200, 200)
template:setSpeed(60, 5, 7)
template:setWarpSpeed(250)
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0,100, -20, 1500.0, 6.0, 8)
template:setBeam(1,100,  20, 1500.0, 6.0, 8)
template:setBeam(2,100, 180, 1500.0, 6.0, 8)
template:setTubes(4, 10.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 12)
template:setWeaponStorage("EMP", 6)
template:setWeaponStorage("Nuke", 2)
template:setTubeDirection(0, -90)
template:setTubeDirection(1, -90)
template:setTubeDirection(2,  90)
template:setTubeDirection(3,  90)

--[[----------------------BattleShip----------------------]]

template = ShipTemplate():setName("Nimitz X53"):setClass("BattleShip", "Flagship"):setModel("battleship_destroyer_4_upgraded")
template:setDescription([[SOL BS]])
template:setRadarTrace("radar_dread.png")
template:setHull(450)
template:setShields(300, 300, 300, 300)
template:setSpeed(60, 5, 7)
template:setWarpSpeed(250)
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0,100, -20, 1500.0, 6.0, 8)
template:setBeam(1,100,  20, 1500.0, 6.0, 8)
template:setBeam(2,100, 180, 1500.0, 6.0, 8)
template:setBeam(3,30, 0, 3000.0, 16.0, 26)
template:setTubes(4, 10.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 16)
template:setWeaponStorage("EMP", 6)
template:setWeaponStorage("Nuke", 2)
template:setTubeDirection(0, -90)
template:setTubeDirection(1, -90)
template:setTubeDirection(2,  90)
template:setTubeDirection(3,  90)


--[[-----------------------Freighters---------------------]]

template = ShipTemplate():setName("Handymax "):setClass("Freighter", "Light Freighter"):setModel("transport_2_1")
template:setDescription([[Need to write]])
template:setHull(100)
template:setShields(50, 50)
template:setSpeed(70, 7, 10)
template:setRadarTrace("radar_transport.png")

template = ShipTemplate():setName("Supramax "):setClass("Freighter", "Medium Freighter"):setModel("transport_2_2")
template:setDescription([[Need to write]])
template:setHull(125)
template:setShields(60, 60)
template:setSpeed(60, 7, 10)
template:setRadarTrace("radar_transport.png")

template = ShipTemplate():setName("VLCC"):setClass("Freighter", "Heavy Freighter"):setModel("transport_2_3")
template:setDescription([[Need to write]])
template:setHull(150)
template:setShields(75, 75)
template:setSpeed(50, 6, 10)
template:setRadarTrace("radar_transport.png")

template = ShipTemplate():setName("Armored VLCC"):setClass("Freighter", "Armored Freighter"):setModel("transport_3_3")
template:setDescription([[Need to write]])
template:setHull(250)
template:setShields(150, 150)
template:setSpeed(40, 5, 10)
template:setRadarTrace("radar_transport.png")

--[[-----------------------Stations---------------------]]

template = ShipTemplate():setName("Small Station"):setModel("space_station_4"):setType("station")
template:setDescription([[stening stations, and security checkpoints. Crews turn over frequently in a small station's cramped accommodatations, but they are small enough to look like ships on many long-range sensors, and organized raiders sometimes take advantage of this by placing small stations in nebulae to serve as raiding bases. They are lightly shielded and vulnerable to swarming assaults.]])
template:setHull(150)
template:setShields(300)
template:setRadarTrace("radartrace_smallstation.png")

template = ShipTemplate():setName("Medium Station"):setModel("space_station_3"):setType("station")
template:setDescription([[Large enough to accommodate small crews for extended periods of times, stations of this size are often trading posts, refuelling bases, mining operations, and forward military bases. While their shields are strong, concerted attacks by many ships can bring them down quickly.]])
template:setHull(400)
template:setShields(800)
template:setRadarTrace("radartrace_mediumstation.png")

template = ShipTemplate():setName("Large Station"):setModel("space_station_2"):setType("station")
template:setDescription([[These spaceborne communities often represent permanent bases in a sector. Stations of this size can be military installations, commercial hubs, deep-space settlements, and small shipyards. Only a concentrated attack can penetrate a large station's shields, and its hull can withstand all but the most powerful weaponry.]])
template:setHull(500)
template:setShields(1000, 1000, 1000)
template:setRadarTrace("radartrace_largestation.png")

template = ShipTemplate():setName("Huge Station"):setModel("space_station_1"):setType("station")
template:setDescription([[The size of a sprawling town, stations at this scale represent a faction's center of spaceborne power in a region. They serve many functions at once and represent an extensive investment of time, money, and labor. A huge station's shields and thick hull can keep it intact long enough for reinforcements to arrive, even when faced with an ongoing siege or massive, perfectly coordinated assault.]])
template:setHull(800)
template:setShields(1200, 1200, 1200, 1200)
template:setRadarTrace("radartrace_hugestation.png")
